apiVersion: v1
kind: Deployment
  metadata: 
    name: nginx-deployment
  spec:
    selector:
      metchLabels:
        app: nginx
      replicas: 2
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 8
    template:
      metadata:
        labels:
          app: nginx
        spec:
          containers:
          - name: nginx
          spec:
          containers:
          - name: nginx
            image: nginx:alpine
            env:
            - name: NGINX_HOST
              value: "diegorojasj.local"
            - name: NGINX_PORT
              value: 80
            resources:
              requests:
                memory: "600Mi"
                cpu: "200m"
            limits:
              memory: "800Mi"
              cpu: "500m"
            # Check Available
            readinessProbe:
              httpGet:
                path: /
                port: 80
              initialDelaySecond: 5
              periodSeconds: 10
            # Open port check
            livenessProbe:
              tcpSocket:
                port: 80
              initialDelaySeconds: 15
              periodSeconds: 20
            ports:
            - containerPort: 80
