apiVersion: v1
kind: Pod
metadata: nginx
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    env:
    - name: NGINX_HOST
      value: "diegorojasj.local"
    - name: NGINX_PORT
      value: 80
    resources:
      requests:
        memory: "600Mi"
        cpu: "200m"
      limits:
        memory: "800Mi"
        cpu: "500m"
  
